name: CI-CD to ECS via ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  AWS_ACCOUNT_ID: 957948932374
  ECR_REPOSITORY: raghu-node-app
  ECS_CLUSTER: raghu-cluster
  ECS_SERVICE: raghu-service

jobs:

# =========================
# BUILD + PUSH
# =========================
  build-and-push:
    runs-on: [self-hosted]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (from EC2 role)
        run: |
          aws sts get-caller-identity

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build Docker Image
        run: |
          docker build -t $ECR_REPOSITORY:${{ github.run_number }} .

      - name: Tag Image
        run: |
          docker tag $ECR_REPOSITORY:${{ github.run_number }} \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:${{ github.run_number }}

      - name: Push Image
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:${{ github.run_number }}

# =========================
# DEPLOY TO ECS
# =========================
  deploy:
    needs: build-and-push
    runs-on: [self-hosted]

    steps:
      - name: Update ECS Service
        run: |
          aws ecs update-service \
            --cluster $ECS_CLUSTER \
            --service $ECS_SERVICE \
            --force-new-deployment \
            --region $AWS_REGION

      - name: Deployment Success
        run: echo "🚀 Deployment completed successfully"
